/* eslint-disable jsx-a11y/alt-text */
import { Image,Page,Text,View,StyleSheet } from "@react-pdf/renderer";
import type { GuideReferenceImage } from "../types/ModelGuide";
import { guidePdfStyles, pdfColors } from "./guidePdfStyles";
import { GuidePageFooter } from "./GuidePageFooter";
import type { Locale } from "@/features/i18n/types/Locale";
import { translate } from "@/features/i18n/lib/i18n";
const styles=StyleSheet.create({grid:{flexDirection:"row",flexWrap:"wrap",gap:14},card:{backgroundColor:"#fafafa",borderColor:pdfColors.border,borderRadius:9,borderStyle:"solid",borderWidth:1,padding:7,width:"48%"},image:{height:184,objectFit:"contain",backgroundColor:"#f5f5f5"},caption:{paddingHorizontal:3,paddingBottom:3},name:{fontSize:10,fontWeight:700,marginTop:8},type:{fontSize:8,color:pdfColors.muted,marginTop:2,textTransform:"capitalize"}});
export function GuideReferencesPage({references,locale}:{references:GuideReferenceImage[];locale:Locale}){const t=(key:Parameters<typeof translate>[1],values?:Parameters<typeof translate>[2])=>translate(locale,key,values);return <Page size="A4" style={guidePdfStyles.page} wrap><Text style={guidePdfStyles.eyebrow}>{t("guide.source")}</Text><Text style={guidePdfStyles.pageTitle}>{t("guide.references")}</Text><Text style={guidePdfStyles.sectionDescription}>{t("pdf.referencesHelp")}</Text><View style={styles.grid}>{references.map(reference=><View key={reference.id} style={styles.card} wrap={false}>{reference.dataUrl?<Image src={reference.dataUrl} style={styles.image}/>:<View style={[styles.image,guidePdfStyles.placeholder]}><Text>{t("pdf.missingView")}</Text></View>}<View style={styles.caption}><Text style={styles.name}>{reference.name}</Text><Text style={styles.type}>{t("guide.referenceType",{type:reference.type})}</Text></View></View>)}</View><GuidePageFooter pageNumber={1} locale={locale}/></Page>}
