"use client";
import Image from "next/image";
import {Image as ImageIcon,X} from "lucide-react";
import {useQuery} from "@tanstack/react-query";
import {useEffect,useState} from "react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import {useObjectUrl} from "../../hooks/useObjectUrl";
import {getAssemblyStepImage} from "../../services/assemblyStepImage.service";
export const assemblyStepImageQueryKey=(projectId:string,stepId:string)=>["assembly-step-image",projectId,stepId] as const;
export function AssemblyStepImage({projectId,stepId,stepNumber,title,hasImage}:{projectId:string;stepId:string;stepNumber:string;title:string;hasImage:boolean}){const {t}=useTranslation(),[preview,setPreview]=useState(false);const query=useQuery({queryKey:assemblyStepImageQueryKey(projectId,stepId),queryFn:()=>getAssemblyStepImage(projectId,stepId),enabled:hasImage,staleTime:Infinity});const url=useObjectUrl(query.data);useEffect(()=>{if(!preview)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setPreview(false);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[preview]);if(!hasImage||(!url&&!query.isLoading))return <div className="flex min-h-28 flex-col items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/15 p-3 text-center"><ImageIcon className="h-5 w-5 text-neutral-600"/><p className="mt-2 text-xs font-medium text-neutral-400">{t("assembly.image.emptyTitle")}</p><p className="mt-1 text-[10px] leading-4 text-neutral-600">{t("assembly.image.emptyDescription")}</p></div>;return <><button type="button" disabled={!url} onClick={()=>setPreview(true)} className="relative block aspect-[4/3] w-full overflow-hidden rounded-xl border border-white/10 bg-black/20">{url?<Image unoptimized fill src={url} alt={t("assembly.image.previewTitle",{number:stepNumber})} className="object-cover"/>:null}</button>{preview&&url?<div className="fixed inset-0 z-50 flex flex-col bg-black/90 p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-orange-300">{t("assembly.image.previewTitle",{number:stepNumber})}</p><p className="text-sm text-white">{title}</p></div><button type="button" onClick={()=>setPreview(false)} aria-label={t("common.close")}><X/></button></div><div className="relative min-h-0 flex-1"><Image unoptimized fill src={url} alt={title} className="object-contain"/></div></div>:null}</>}
