"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Image from "next/image";
import {Plus,Trash2,X} from "lucide-react";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import {useModelEditorStore} from "../store/modelEditorStore";
import type {PaintingStage,PaintingStepPreviewShot} from "../types/PaintingWorkflow";
import {getPaintingStageLabel} from "../lib/paintingStageLabel";
import {getStepPreviewCacheKey} from "./getStepPreviewCacheKey";
import {getOrGenerateStepPreview} from "./stepPreviewService";
import {invalidateStepPreview} from "./cache";
import type {StepPreviewErrorCode,StepPreviewResult} from "./types";

function normalizeError(error:unknown):StepPreviewErrorCode{if(error instanceof Error&&["modelUnavailable","targetsUnavailable","renderUnavailable","generationCancelled"].includes(error.message))return error.message as StepPreviewErrorCode;return"unknown"}

export function StepPreview({projectId,step}:{projectId:string;step:PaintingStage}){
 const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),details=useModelEditorStore(s=>s.manualDetails),palette=useModelEditorStore(s=>s.palette),add=useModelEditorStore(s=>s.addPaintingStagePreviewShot),remove=useModelEditorStore(s=>s.removePaintingStagePreviewShot),setOverview=useModelEditorStore(s=>s.setPaintingStageOverviewPreviewEnabled),[choosing,setChoosing]=useState(false),addButtonRef=useRef<HTMLButtonElement>(null),part=parts.find(item=>item.paintingWorkflow.stages.some(candidate=>candidate.id===step.id)),targetIds=new Set(step.targetReferences?.filter(reference=>reference.type==="manualDetail").map(reference=>reference.id)),targetDetails=details.filter(detail=>targetIds.has(detail.id)),shots=step.previewShots??[],overviewEnabled=step.overviewPreviewEnabled!==false,added=new Set(shots.map(shot=>`${shot.manualDetailId}:${shot.pinId}`)),title=getPaintingStageLabel(step,t);
 function removeShot(shot:PaintingStepPreviewShot){if(!part)return;invalidateStepPreview(getStepPreviewCacheKey(projectId,step,parts,details,palette,shot));remove(part.id,step.id,shot.id)}
 function closeChooser(){setChoosing(false);requestAnimationFrame(()=>addButtonRef.current?.focus())}
 function removeOverview(){if(!part)return;invalidateStepPreview(getStepPreviewCacheKey(projectId,step,parts,details,palette));setOverview(part.id,step.id,false)}
 function restoreOverview(){if(part)setOverview(part.id,step.id,true)}
 return <section className="mt-3 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-3"><div className="flex items-center justify-between gap-2"><div><h4 className="text-xs font-semibold">{t("editor.steps.preview.title")}</h4><p className="text-[10px] text-[var(--text-secondary)]">{t("editor.steps.preview.automatic")}</p></div><div className="flex flex-wrap justify-end gap-2">{!overviewEnabled?<button type="button" onClick={restoreOverview} className="text-xs text-[var(--accent)]">{t("editor.steps.previewShots.restoreOverview")}</button>:null}{targetDetails.length?<button ref={addButtonRef} type="button" onClick={()=>setChoosing(true)} className="flex items-center gap-1 text-xs text-[var(--accent)]"><Plus className="size-3"/>{t("editor.steps.previewShots.addAnother")}</button>:null}</div></div>{overviewEnabled||shots.length?<div className="mt-3 grid gap-3 sm:grid-cols-2">{overviewEnabled?<PreviewImage projectId={projectId} step={step} label={t("editor.steps.previewShots.automaticOverview")} title={title} onRemove={removeOverview}/>:null}{shots.map(shot=>{const detail=details.find(item=>item.id===shot.manualDetailId),index=detail?.pins.findIndex(pin=>pin.id===shot.pinId)??-1,label=detail&&index>=0?t("editor.steps.previewShots.detailLabel",{number:detail.number,name:detail.name,index:index+1}):t("editor.steps.previewShots.unavailable");return <PreviewImage key={shot.id} projectId={projectId} step={step} shot={shot} label={label} title={title} unavailable={!detail||index<0} onRemove={()=>removeShot(shot)}/>})}</div>:null}{choosing?<div role="dialog" aria-modal="true" aria-label={t("editor.steps.previewShots.chooseLocation")} className="mt-3 rounded-lg border border-[var(--border)] bg-[var(--card)] p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold">{t("editor.steps.previewShots.chooseLocation")}</p><button autoFocus type="button" aria-label={t("common.close")} onClick={closeChooser}><X className="size-4"/></button></div><div className="mt-2 space-y-3">{targetDetails.map(detail=><section key={detail.id}><p className="text-xs font-medium">{t("editor.manualDetails.detailLabel",{number:detail.number,name:detail.name})}</p><div className="mt-1 flex flex-wrap gap-1">{detail.pins.map((pin,index)=>{const exists=added.has(`${detail.id}:${pin.id}`);return <button key={pin.id} type="button" disabled={exists} title={exists?t("editor.steps.previewShots.alreadyAdded"):undefined} onClick={()=>{if(part){add(part.id,step.id,detail.id,pin.id);closeChooser()}}} className="rounded-lg border border-[var(--border)] px-2 py-1 text-xs disabled:opacity-40">{t("editor.steps.previewShots.location",{index:index+1})}</button>})}</div></section>)}</div><button type="button" onClick={closeChooser} className="mt-3 text-xs text-[var(--text-secondary)]">{t("common.cancel")}</button></div>:null}</section>
}

function PreviewImage({projectId,step,shot,label,title,unavailable=false,onRemove}:{projectId:string;step:PaintingStage;shot?:PaintingStepPreviewShot;label:string;title:string;unavailable?:boolean;onRemove?:()=>void}){
 const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),details=useModelEditorStore(s=>s.manualDetails),palette=useModelEditorStore(s=>s.palette),key=useMemo(()=>getStepPreviewCacheKey(projectId,step,parts,details,palette,shot),[details,palette,parts,projectId,shot,step]),[result,setResult]=useState<StepPreviewResult|null>(null),[error,setError]=useState<StepPreviewErrorCode|null>(null),[loading,setLoading]=useState(false),request=useRef(0),hasTargets=Boolean(step.targetReferences?.length);
 const generate=useCallback(async(force=false)=>{if(!hasTargets||unavailable)return;const token=++request.current;setLoading(true);setError(null);try{const next=await getOrGenerateStepPreview(projectId,step.id,key,force,shot);if(token===request.current)setResult(next)}catch(runtimeError){if(token===request.current){setResult(null);setError(normalizeError(runtimeError))}}finally{if(token===request.current)setLoading(false)}},[hasTargets,key,projectId,shot,step.id,unavailable]);
 useEffect(()=>{void generate();return()=>{request.current+=1}},[generate]);
 return <figure className="overflow-hidden rounded-lg border border-[var(--border)] bg-[#F7F7F5]"><div className="flex min-h-8 items-center justify-between bg-[var(--card)] px-2"><figcaption className="truncate text-[10px] text-[var(--text-secondary)]">{label}</figcaption>{onRemove?<button type="button" onClick={onRemove} aria-label={t("editor.steps.previewShots.accessibility.remove",{label})} className="text-red-500"><Trash2 className="size-3.5"/></button>:null}</div><div className="relative aspect-[3/2]">{!hasTargets?<div className="grid h-full place-items-center p-3 text-center text-xs text-neutral-500">{t("editor.steps.preview.general")}</div>:unavailable?<div className="grid h-full place-items-center p-3 text-center text-xs text-neutral-500">{t("editor.steps.previewShots.missingLocation")}</div>:loading?<div role="status" className="grid h-full place-items-center text-xs text-neutral-500">{t("editor.steps.preview.generating")}</div>:result?<Image unoptimized fill sizes="320px" src={result.imageUrl} alt={shot?t("editor.steps.previewShots.accessibility.alt",{title,label}):t("editor.steps.preview.accessibility.alt",{title})} className="object-contain"/>:<button type="button" onClick={()=>void generate(true)} className="grid h-full w-full place-items-center p-3 text-center text-xs text-neutral-500">{t(`editor.steps.preview.errors.${error??"unknown"}`)}</button>}</div></figure>
}
