"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Image from "next/image";
import { useCallback,useEffect,useRef,useState } from "react";
import { useTranslation } from "@/features/i18n/hooks/useTranslation";
import type { PaintingStage } from "../types/PaintingWorkflow";
import { useModelEditorStore } from "../store/modelEditorStore";
import { getStepPreviewCacheKey } from "./getStepPreviewCacheKey";
import { getOrGenerateStepPreview } from "./stepPreviewService";
import type { StepPreviewErrorCode,StepPreviewResult } from "./types";
import { getPaintingStageLabel } from "../lib/paintingStageLabel";
function normalizeError(error:unknown):StepPreviewErrorCode{if(error instanceof Error&&["modelUnavailable","targetsUnavailable","renderUnavailable","generationCancelled"].includes(error.message))return error.message as StepPreviewErrorCode;return"unknown"}
export function StepPreview({projectId,step}:{projectId:string;step:PaintingStage}){const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),markers=useModelEditorStore(s=>s.markers),key=getStepPreviewCacheKey(projectId,step,parts,markers),[result,setResult]=useState<StepPreviewResult|null>(null),[error,setError]=useState<StepPreviewErrorCode|null>(null),[loading,setLoading]=useState(false),request=useRef(0),hasTargets=Boolean(step.targetReferences?.length);const generate=useCallback(async(force=false)=>{if(!hasTargets)return;const token=++request.current;setLoading(true);setError(null);try{const next=await getOrGenerateStepPreview(projectId,step.id,key,force);if(token===request.current)setResult(next)}catch(runtimeError){if(token===request.current){setResult(null);setError(normalizeError(runtimeError))}}finally{if(token===request.current)setLoading(false)}},[hasTargets,key,projectId,step.id]);useEffect(()=>{void generate();return()=>{request.current+=1}},[generate]);const title=getPaintingStageLabel(step,t);return <section className="mt-3 overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--bg)]"><div className="flex items-center justify-between gap-2 px-3 py-2"><div><h4 className="text-xs font-semibold">{t("editor.steps.preview.title")}</h4><p className="text-[10px] text-[var(--text-secondary)]">{t("editor.steps.preview.automatic")}</p></div>{hasTargets&&!loading?<button type="button" onClick={()=>void generate(true)} aria-label={t("editor.steps.preview.accessibility.update",{title})} className="text-xs text-[var(--accent)]">{t(error?"editor.steps.preview.retry":"editor.steps.preview.update")}</button>:null}</div><div className="relative aspect-[3/2] w-full bg-[#F7F7F5]">{!hasTargets?<div className="grid h-full place-items-center p-4 text-center text-xs text-neutral-500">{t("editor.steps.preview.general")}</div>:loading?<div role="status" className="grid h-full place-items-center text-xs text-neutral-500"><span className="animate-pulse">{t("editor.steps.preview.generating")}</span></div>:result?<Image unoptimized fill sizes="320px" src={result.imageUrl} alt={t("editor.steps.preview.accessibility.alt",{title})} className="object-contain"/>:<div role="status" className="grid h-full place-items-center p-4 text-center text-xs text-neutral-500">{t(`editor.steps.preview.errors.${error??"unknown"}`)}</div>}</div></section>}
