"use client";
import {Check,X} from "lucide-react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import {useModelEditorStore} from "../../store/modelEditorStore";
import type {PaintingTargetReference} from "../../types/PaintingWorkflow";
const key=(reference:PaintingTargetReference)=>`${reference.type}:${reference.id}`;
export function PaintingTargetPicker({value,onChange}:{value:PaintingTargetReference[];onChange:(value:PaintingTargetReference[])=>void}){
 const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),details=useModelEditorStore(s=>s.manualDetails),palette=useModelEditorStore(s=>s.palette),colors=new Map(palette.map(color=>[color.id,color])),selected=new Set(value.map(key));
 const toggle=(reference:PaintingTargetReference)=>onChange(selected.has(key(reference))?value.filter(item=>key(item)!==key(reference)):[...value,reference]);
 const chips=[...new Map(value.flatMap(reference=>{if(reference.type==="part"){const part=parts.find(item=>item.id===reference.id);return part?[{reference,name:part.name}]:[]}const detail=details.find(item=>item.id===reference.id);return detail?[{reference,name:t("editor.manualDetails.detailLabel",{number:detail.number,name:detail.name})}]:[]}).map(item=>[key(item.reference),item])).values()];
 return <fieldset className="space-y-3"><legend className="text-xs text-neutral-400">{t("editor.steps.targets.appliesTo")}</legend>{chips.length?<div className="flex flex-wrap gap-1.5">{chips.map(({reference,name})=><span key={key(reference)} title={name} className="flex max-w-full items-center gap-1 rounded-full border border-white/10 px-2 py-1 text-xs"><span className="truncate">{name}</span><button type="button" onClick={()=>toggle(reference)} aria-label={t("editor.steps.accessibility.removeTarget",{name})}><X className="size-3"/></button></span>)}</div>:<p className="text-xs text-neutral-500">{t("editor.steps.targets.general")}</p>}<div className="max-h-52 space-y-3 overflow-y-auto rounded-xl border border-white/10 p-3"><TargetGroup title={t("editor.steps.targets.detected")} type="part" items={parts.map(part=>({id:part.id,name:part.name,color:part.paletteColorId?colors.get(part.paletteColorId)?.hex:null}))} selected={selected} toggle={toggle}/><TargetGroup title={t("editor.steps.targets.manualDetails")} type="manualDetail" items={details.map(detail=>({id:detail.id,name:t("editor.manualDetails.detailLabel",{number:detail.number,name:detail.name}),meta:t("editor.manualDetails.locationCount",{count:detail.pins.length}),color:detail.colorId?colors.get(detail.colorId)?.hex:null}))} selected={selected} toggle={toggle}/></div>{value.length?<button type="button" onClick={()=>onChange([])} className="text-xs text-neutral-400 underline">{t("editor.steps.targets.clear")}</button>:null}</fieldset>
}
function TargetGroup({title,items,type,selected,toggle}:{title:string;items:Array<{id:string;name:string;meta?:string;color?:string|null}>;type:"part"|"manualDetail";selected:Set<string>;toggle:(reference:PaintingTargetReference)=>void}){return <section aria-label={title}><h3 className="text-xs font-semibold text-neutral-300">{title}</h3>{items.length?<div className="mt-2 space-y-1">{items.map(item=>{const checked=selected.has(`${type}:${item.id}`);return <button key={item.id} type="button" role="checkbox" aria-checked={checked} onClick={()=>toggle({type,id:item.id})} className="flex min-h-9 w-full items-center gap-2 rounded-lg px-2 text-left text-xs hover:bg-white/5"><span className={`grid size-4 place-items-center rounded border ${checked?"border-orange-400 bg-orange-400 text-black":"border-white/20"}`}>{checked?<Check className="size-3"/>:null}</span>{item.color?<span className="size-3 rounded-full" style={{backgroundColor:item.color}}/>:null}<span className="min-w-0 flex-1"><span className="block truncate">{item.name}</span>{item.meta?<span className="block text-[10px] text-neutral-500">{item.meta}</span>:null}</span></button>})}</div>:<p className="mt-2 text-xs text-neutral-600">—</p>}</section>}
