"use client";
import {Check} from "lucide-react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import {useModelEditorStore} from "../../store/modelEditorStore";
import type {PaintingTargetReference} from "../../types/PaintingWorkflow";
const key=(reference:PaintingTargetReference)=>`${reference.type}:${reference.id}`;
export function PaintingTargetPicker({value,onChange}:{value:PaintingTargetReference[];onChange:(value:PaintingTargetReference[])=>void}){
 const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),details=useModelEditorStore(s=>s.manualDetails),palette=useModelEditorStore(s=>s.palette),colors=new Map(palette.map(color=>[color.id,color])),selected=new Set(value.map(key));
 const toggle=(reference:PaintingTargetReference)=>onChange(selected.has(key(reference))?value.filter(item=>key(item)!==key(reference)):[...value.filter(item=>key(item)!==key(reference)),reference]);
 const detected=parts.map(part=>({id:part.id,name:part.name,color:part.paletteColorId?colors.get(part.paletteColorId)??null:null})),manual=details.map(detail=>({id:detail.id,name:t("editor.manualDetails.detailLabel",{number:detail.number,name:detail.name}),color:detail.colorId?colors.get(detail.colorId)??null:null}));
 return <fieldset><div className="flex items-center justify-between gap-3"><legend className="text-xs text-[var(--text-secondary)]">{t("painting.form.targetDetails")}</legend><span aria-live="polite" className="text-[10px] text-[var(--text-secondary)]">{t("painting.form.selectedCount",{count:selected.size})}</span></div><p className="mt-1 text-[10px] text-[var(--text-secondary)]">{t("editor.steps.targets.general")}</p><div className="mt-2 max-h-56 space-y-4 overflow-y-auto rounded-lg border border-[var(--border)] p-2"><TargetGroup title={t("editor.steps.targets.detected")} type="part" items={detected} selected={selected} toggle={toggle} noColor={t("painting.form.noColorAssigned")}/><TargetGroup title={t("editor.steps.targets.manualDetails")} type="manualDetail" items={manual} selected={selected} toggle={toggle} noColor={t("painting.form.noColorAssigned")}/></div></fieldset>
}
function TargetGroup({title,items,type,selected,toggle,noColor}:{title:string;items:Array<{id:string;name:string;color:{name:string;hex:string}|null}>;type:"part"|"manualDetail";selected:Set<string>;toggle:(reference:PaintingTargetReference)=>void;noColor:string}){return <section aria-label={title}><h3 className="px-2 text-[10px] font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{title}</h3>{items.length?<div className="mt-1 space-y-1">{items.map(item=>{const checked=selected.has(`${type}:${item.id}`);return <button key={item.id} type="button" role="checkbox" aria-checked={checked} onClick={()=>toggle({type,id:item.id})} className={`flex min-h-11 w-full items-center gap-3 rounded-lg px-2 text-left text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] ${checked?"bg-[var(--bg)] ring-1 ring-[var(--accent)]":"hover:bg-[var(--bg)]"}`}><span aria-hidden="true" className={`grid size-4 shrink-0 place-items-center rounded border ${checked?"border-[var(--accent)] bg-[var(--accent)] text-[var(--accent-foreground)]":"border-[var(--border)]"}`}>{checked?<Check className="size-3"/>:null}</span><span className="min-w-0 flex-1"><span className="block truncate font-medium">{item.name}</span><span className="mt-0.5 flex items-center gap-1.5 truncate text-[10px] text-[var(--text-secondary)]">{item.color?<><span aria-hidden="true" className="size-2.5 shrink-0 rounded-full border border-[var(--border)]" style={{backgroundColor:item.color.hex}}/><span className="truncate">{item.color.name}</span></>:noColor}</span></span></button>})}</div>:<p className="px-2 py-2 text-xs text-[var(--text-secondary)]">—</p>}</section>}
