"use client";
import { useState } from "react";
import { Copy,Library,Save } from "lucide-react";
import { useTranslation } from "@/features/i18n/hooks/useTranslation";
import { useModelEditorStore } from "../../store/modelEditorStore";
import type { ModelPart } from "../../types/ModelPart";
import type { PaintingWorkflowPreset } from "../../types/PaintingWorkflow";
import { createWorkflowStagesFromPreset } from "../../lib/paintingWorkflowPresets";
import { paintingWorkflowPresetRepository } from "../../storage/paintingWorkflowPresetRepository";
import { PaintingWorkflowTemplateModal } from "./PaintingWorkflowTemplateModal";
import { SavePaintingWorkflowPresetModal } from "./SavePaintingWorkflowPresetModal";
export function PaintingWorkflowReuseActions({part}:{part:ModelPart}){const{t}=useTranslation();const[templates,setTemplates]=useState(false),[saving,setSaving]=useState(false);const parts=useModelEditorStore(s=>s.parts),palette=useModelEditorStore(s=>s.palette),replace=useModelEditorStore(s=>s.replacePartPaintingWorkflow),copy=useModelEditorStore(s=>s.copyPaintingWorkflowFromPart);function applyPreset(preset:PaintingWorkflowPreset,replaceDetails:boolean){const{stages}=createWorkflowStagesFromPreset({preset,palette,getStageName:type=>t(`painting.stageTypes.${type}`)});replace(part.id,replaceDetails?{stages,notes:"",paintBeforeAssembly:false,difficulty:null,estimatedTimeMinutes:null}:{...part.paintingWorkflow,stages})}return <div className="border-t border-white/10 px-4 pb-4 pt-3 sm:px-5"><div className="flex flex-wrap gap-2"><button onClick={()=>setTemplates(true)} className="flex items-center gap-1.5 rounded-lg border border-white/10 px-2.5 py-2 text-xs text-neutral-300"><Library className="h-3.5 w-3.5"/>{t("painting.templates.applyAction")}</button><button onClick={()=>setTemplates(true)} className="flex items-center gap-1.5 rounded-lg border border-white/10 px-2.5 py-2 text-xs text-neutral-300"><Copy className="h-3.5 w-3.5"/>{t("painting.copyWorkflow.action")}</button><button disabled={!part.paintingWorkflow.stages.length} onClick={()=>setSaving(true)} className="flex items-center gap-1.5 rounded-lg border border-white/10 px-2.5 py-2 text-xs text-neutral-300 disabled:opacity-35"><Save className="h-3.5 w-3.5"/>{t("painting.savePreset.action")}</button></div>{templates?<PaintingWorkflowTemplateModal target={part} parts={parts} onClose={()=>setTemplates(false)} onApplyPreset={applyPreset} onCopy={(source,details)=>copy(source.id,part.id,details)}/>:null}{saving?<SavePaintingWorkflowPresetModal workflow={part.paintingWorkflow} onClose={()=>setSaving(false)} onSaved={preset=>paintingWorkflowPresetRepository.saveUserPaintingWorkflowPreset(preset)}/>:null}</div>}
