"use client";
import { useState } from "react";
import { X } from "lucide-react";
import { useTranslation } from "@/features/i18n/hooks/useTranslation";
import { getPaintingStageLabel } from "../../lib/paintingStageLabel";
import type { PartPaintingWorkflow, PaintingWorkflowPreset } from "../../types/PaintingWorkflow";
import { toStagePresets } from "../../lib/paintingWorkflowPresets";
export function SavePaintingWorkflowPresetModal({workflow,onClose,onSaved}:{workflow:PartPaintingWorkflow;onClose:()=>void;onSaved:(preset:PaintingWorkflowPreset)=>Promise<void>}){
 const{t}=useTranslation();const[name,setName]=useState(""),[description,setDescription]=useState(""),[saving,setSaving]=useState(false),[failed,setFailed]=useState(false);const valid=Boolean(name.trim())&&name.length<=100&&description.length<=300&&workflow.stages.length>0;
 async function submit(){if(!valid||saving)return;setSaving(true);setFailed(false);const now=new Date().toISOString();try{await onSaved({id:crypto.randomUUID(),source:"user",name:name.trim(),description:description.trim(),stages:toStagePresets(workflow),createdAt:now,updatedAt:now});onClose()}catch{setFailed(true);setSaving(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><form onSubmit={e=>{e.preventDefault();void submit()}} className="w-full max-w-md rounded-3xl border border-white/10 bg-neutral-900"><header className="flex items-center justify-between border-b border-white/10 p-5"><h2 className="text-lg font-semibold">{t("painting.savePreset.title")}</h2><button type="button" onClick={onClose} aria-label={t("common.close")}><X className="h-5 w-5"/></button></header><div className="space-y-4 p-5">{workflow.stages.length===0?<p className="text-sm text-amber-300">{t("painting.presetValidation.empty")}</p>:null}<label className="block text-xs text-neutral-400">{t("painting.savePreset.name")}<input autoFocus maxLength={100} value={name} onChange={e=>setName(e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-black/20 px-3"/></label><label className="block text-xs text-neutral-400">{t("painting.savePreset.description")}<textarea maxLength={300} rows={3} value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3"/></label><div className="rounded-xl border border-white/10 p-3"><p className="text-xs text-neutral-500">{t("painting.templates.stageCount",{count:workflow.stages.length})}</p><p className="mt-2 text-xs text-neutral-300">{workflow.stages.map(s=>getPaintingStageLabel(s,t)).join(" · ")}</p></div>{failed?<p className="text-xs text-red-300">{t("painting.presetErrors.save")}</p>:null}</div><footer className="flex justify-end gap-2 border-t border-white/10 p-4"><button type="button" onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2">{t("common.cancel")}</button><button disabled={!valid||saving} className="rounded-xl bg-orange-400 px-4 py-2 font-semibold text-black disabled:opacity-40">{t("painting.savePreset.save")}</button></footer></form></div>
}
