"use client";
import {useState} from "react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import type {CreatePaintingStageInput,PaintingStage,PaintingStageType,PaintingTargetReference} from "../../types/PaintingWorkflow";
import {PAINTING_STAGE_TYPES} from "../../lib/paintingWorkflow";
import {getPaintingStageTypeLabel} from "../../lib/paintingStageLabel";
import {getStepsReferencingManualDetail} from "../../lib/paintingTargets";
import {useModelEditorStore} from "../../store/modelEditorStore";
import {StepPreview} from "../../step-previews/StepPreview";
import {StepDetailsAndMarkers} from "./StepDetailsAndMarkers";

type Props={stage:PaintingStage;projectId:string;activeReferenceId?:string|null;onSelectReference?:(id:string)=>void;onShowReference?:(id:string)=>void;onReferenceDeleted?:(id:string)=>void;onClose:()=>void;onSave:(input:CreatePaintingStageInput)=>void};
export function SimplePaintingStepEditor({stage,projectId,onClose,onSave}:Props){
 const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),update=useModelEditorStore(s=>s.updatePaintingStage),deleteDetail=useModelEditorStore(s=>s.deleteManualDetail);
 const[type,setType]=useState<PaintingStageType>(stage.type),[title,setTitle]=useState(stage.customName??getPaintingStageTypeLabel(stage.type,t)),[notes,setNotes]=useState(stage.notes),[targets,setTargets]=useState(stage.targetReferences??[]);
 const valid=Boolean(title.trim())&&title.length<=100&&notes.length<=500,isPrimer=type==="primer";
 function targetsChanged(value:PaintingTargetReference[]){const nextKeys=new Set(value.map(reference=>`${reference.type}:${reference.id}`));for(const reference of stage.targetReferences??[])if(!nextKeys.has(`${reference.type}:${reference.id}`)&&reference.type==="manualDetail"&&getStepsReferencingManualDetail(parts,reference.id).length<=1)deleteDetail(reference.id);setTargets(value);const owner=parts.find(part=>part.paintingWorkflow.stages.some(item=>item.id===stage.id));if(owner)update(owner.id,stage.id,{targetReferences:value})}
 return <form onSubmit={event=>{event.preventDefault();if(valid)onSave({type,customName:title.trim(),paletteColorId:stage.paletteColorId,recommendedCoats:stage.recommendedCoats,notes:notes.trim(),targetReferences:targets,overviewPreviewEnabled:stage.overviewPreviewEnabled,previewShots:stage.previewShots})}} className="mt-3 space-y-4 border-l-2 border-[var(--accent)] pl-3"><section><h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{t("editor.workflow.stepInformation")}</h4><div className="space-y-3"><label className="block text-xs">{t("painting.form.stepTitle")}<input autoFocus value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--card)] px-3"/></label><label className="block text-xs">{t("painting.form.stage")}<select value={type} onChange={e=>setType(e.target.value as PaintingStageType)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--card)] px-3">{PAINTING_STAGE_TYPES.map(value=><option key={value} value={value}>{getPaintingStageTypeLabel(value,t)}</option>)}</select></label><label className="block text-xs">{t("painting.form.instruction")}<textarea rows={3} maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--card)] p-3"/></label></div></section>{isPrimer?<dl className="flex gap-3 border-y border-[var(--border)] py-3 text-xs"><dt className="font-semibold">{t("editor.workflow.target")}</dt><dd className="text-[var(--text-secondary)]">{t("editor.workflow.entireModel")}</dd></dl>:<StepDetailsAndMarkers value={targets} onChange={targetsChanged}/>}<section className="border-t border-[var(--border)] pt-3"><h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{t("editor.workflow.stepPreview")}</h4><StepPreview projectId={projectId} step={stage}/></section><div className="flex justify-end gap-2 border-t border-[var(--border)] pt-4"><button type="button" onClick={onClose} className="rounded-lg border border-[var(--border)] px-4 py-2">{t("common.cancel")}</button><button disabled={!valid} className="rounded-lg bg-[var(--accent)] px-4 py-2 text-[var(--accent-foreground)] disabled:opacity-40">{t("painting.form.saveStep")}</button></div></form>
}
