"use client";
import {useState} from "react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import type {CreatePaintingStageInput,PaintingStage,PaintingStageType,PaintingTargetReference} from "../../types/PaintingWorkflow";
import {PAINTING_STAGE_TYPES} from "../../lib/paintingWorkflow";
import {getPaintingStageTypeLabel} from "../../lib/paintingStageLabel";
import {getStepsReferencingManualDetail} from "../../lib/paintingTargets";
import {useModelEditorStore} from "../../store/modelEditorStore";
import {StepPreview} from "../../step-previews/StepPreview";
import {StepDetailsAndMarkers} from "./StepDetailsAndMarkers";

type Props={stage:PaintingStage;projectId:string;activeReferenceId?:string|null;onSelectReference?:(id:string)=>void;onShowReference?:(id:string)=>void;onReferenceDeleted?:(id:string)=>void;onClose:()=>void;onSave:(input:CreatePaintingStageInput)=>void};
export function SimplePaintingStepEditor({stage,projectId,onClose,onSave}:Props){
 const{t}=useTranslation(),parts=useModelEditorStore(s=>s.parts),update=useModelEditorStore(s=>s.updatePaintingStage),deleteDetail=useModelEditorStore(s=>s.deleteManualDetail);
 const[type,setType]=useState<PaintingStageType>(stage.type),[title,setTitle]=useState(stage.customName??getPaintingStageTypeLabel(stage.type,t)),[notes,setNotes]=useState(stage.notes),[targets,setTargets]=useState(stage.targetReferences??[]);
 const valid=Boolean(title.trim())&&title.length<=100&&notes.length<=500,isPrimer=type==="primer";
 function targetsChanged(value:PaintingTargetReference[]){const nextKeys=new Set(value.map(reference=>`${reference.type}:${reference.id}`));for(const reference of stage.targetReferences??[])if(!nextKeys.has(`${reference.type}:${reference.id}`)&&reference.type==="manualDetail"&&getStepsReferencingManualDetail(parts,reference.id).length<=1)deleteDetail(reference.id);setTargets(value);const owner=parts.find(part=>part.paintingWorkflow.stages.some(item=>item.id===stage.id));if(owner)update(owner.id,stage.id,{targetReferences:value})}
 return <form onSubmit={event=>{event.preventDefault();if(valid)onSave({type,customName:title.trim(),paletteColorId:stage.paletteColorId,recommendedCoats:stage.recommendedCoats,notes:notes.trim(),targetReferences:targets,overviewPreviewEnabled:stage.overviewPreviewEnabled,previewShots:stage.previewShots})}} className="simple-step-editor mt-3 space-y-3"><section><div className="space-y-2.5"><label className="simple-editor-label block text-[10px] font-semibold uppercase tracking-wide">{t("painting.form.stepTitle")}<input autoFocus value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} className="simple-editor-control mt-1 h-10 w-full px-3 text-sm normal-case tracking-normal"/></label><label className="simple-editor-label block text-[10px] font-semibold uppercase tracking-wide">{t("painting.form.stage")}<select value={type} onChange={e=>setType(e.target.value as PaintingStageType)} className="simple-editor-control mt-1 h-10 w-full cursor-pointer px-3 text-sm normal-case tracking-normal">{PAINTING_STAGE_TYPES.map(value=><option key={value} value={value}>{getPaintingStageTypeLabel(value,t)}</option>)}</select></label><label className="simple-editor-label block text-[10px] font-semibold uppercase tracking-wide">{t("painting.form.instruction")}<textarea rows={3} maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} className="simple-editor-control mt-1 min-h-20 w-full resize-y p-3 text-sm normal-case tracking-normal"/></label></div></section><section className="simple-editor-section border-t pt-3">{isPrimer?<dl className="flex gap-3 text-xs"><dt className="font-semibold">{t("editor.workflow.target")}</dt><dd className="text-[var(--text-muted)]">{t("editor.workflow.entireModel")}</dd></dl>:<StepDetailsAndMarkers value={targets} onChange={targetsChanged}/>}</section><section className="simple-editor-section border-t pt-3"><div className="flex items-center gap-3"><h4 className="simple-editor-heading text-[10px] font-semibold uppercase tracking-wider">{t("editor.workflow.stepPreview")}</h4><span aria-hidden="true" className="h-px flex-1 bg-[var(--border)]"/></div><StepPreview projectId={projectId} step={stage}/></section><div className="simple-editor-footer flex items-center justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="simple-editor-cancel min-h-9 cursor-pointer rounded-lg px-3 text-sm font-medium">{t("common.cancel")}</button><button disabled={!valid} className="simple-editor-save min-h-9 cursor-pointer rounded-lg px-4 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-40">{t("painting.form.saveStep")}</button></div></form>
}
