"use client";
import {ArrowDown,ArrowUp,Boxes,Check,Copy,GripVertical,MapPin,Paintbrush,Pencil,Plus,RotateCcw,Trash2} from "lucide-react";
import {useEffect,useLayoutEffect,useMemo,useRef,useState,type DragEvent} from "react";
import {ConfirmationModal} from "@/components/ui/ConfirmationModal";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import {getPaintingStageLabel,getPaintingStageTypeLabel} from "../../lib/paintingStageLabel";
import {useModelEditorStore} from "../../store/modelEditorStore";
import {invalidatePaintingStepPreview} from "../../step-previews/stepPreviewService";
import type {PaintingStage} from "../../types/PaintingWorkflow";
import type {ManualDetail} from "@/features/models/types/ManualDetail";
import {SimplePaintingStepEditor} from "./SimplePaintingStepEditor";
import {getLegacyTargetModeCounts,type SimpleTargetMode} from "../../lib/simpleTargetMode";
import {useSimplePartSelection} from "../../hooks/useSimplePartSelection";
import {ONBOARDING_TARGETS} from "@/features/onboarding/constants/onboardingTargets";
import {ContextualHintSlot} from "@/features/onboarding/components/ContextualHintSlot";
import {canUseSimplePartColoring} from "../../lib/canUseSimplePartColoring";

type Props={projectId:string;activeReferenceId:string|null;onSelectReference:(id:string)=>void;onShowReference:(id:string)=>void;onReferenceDeleted:(id:string)=>void};
export function SimplePaintingSteps(props:Props){
 const{t}=useTranslation(),{projectId}=props,{parts}=useSimplePartSelection(),details=useModelEditorStore(s=>s.manualDetails),palette=useModelEditorStore(s=>s.palette),simpleTargetMode=useModelEditorStore(s=>s.simpleTargetMode),simplePaintingStepOrder=useModelEditorStore(s=>s.simplePaintingStepOrder),applySimpleTargetMode=useModelEditorStore(s=>s.applySimpleTargetMode),selectPart=useModelEditorStore(s=>s.selectPart),add=useModelEditorStore(s=>s.addPaintingStage),update=useModelEditorStore(s=>s.updatePaintingStage),removeSimpleStep=useModelEditorStore(s=>s.deleteSimplePaintingStage),reorder=useModelEditorStore(s=>s.reorderSimplePaintingStage),duplicate=useModelEditorStore(s=>s.duplicatePaintingStage),setActive=useModelEditorStore(s=>s.setActivePaintingStage),[editingId,setEditingId]=useState<string|null>(null),[draftStage,setDraftStage]=useState<PaintingStage|null>(null),[,setDraftPartId]=useState<string|null>(null),[deleting,setDeleting]=useState<PaintingStage|null>(null),[changingMode,setChangingMode]=useState(false),[draggedId,setDraggedId]=useState<string|null>(null),[dropIndex,setDropIndex]=useState<number|null>(null);
 const snapshotRef=useRef<{manualDetails:ManualDetail[];nextManualDetailNumber:number;stage:PaintingStage|null;partId:string}|null>(null),dragOverlayRef=useRef<HTMLElement|null>(null),stepElementsRef=useRef(new Map<string,HTMLElement>()),preReorderRectsRef=useRef<Map<string,DOMRect>|null>(null);
 const[draggedHeight,setDraggedHeight]=useState(0);
 const part=parts[0]??null;
 const stages=useMemo(()=>{const all=parts.flatMap(owner=>owner.paintingWorkflow.stages),byId=new Map(all.map(stage=>[stage.id,stage]));return[...simplePaintingStepOrder.map(id=>byId.get(id)).filter((stage):stage is PaintingStage=>Boolean(stage)),...all.filter(stage=>!simplePaintingStepOrder.includes(stage.id))]},[parts,simplePaintingStepOrder]);
 const stageOrderKey=stages.map(stage=>stage.id).join("|");
 useLayoutEffect(()=>{const previous=preReorderRectsRef.current;if(!previous)return;preReorderRectsRef.current=null;if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;for(const[id,before]of previous){const element=stepElementsRef.current.get(id);if(!element)continue;const after=element.getBoundingClientRect(),x=before.left-after.left,y=before.top-after.top;if(!x&&!y)continue;element.animate([{transform:`translate(${x}px, ${y}px)`},{transform:"translate(0, 0)"}],{duration:220,easing:"cubic-bezier(.2,.8,.2,1)"})}},[stageOrderKey]);
 useEffect(()=>()=>{dragOverlayRef.current?.remove()},[]);
 function captureSnapshot(ownerId:string,stage:PaintingStage|null){const state=useModelEditorStore.getState();snapshotRef.current={manualDetails:structuredClone(state.manualDetails),nextManualDetailNumber:state.nextManualDetailNumber,stage:stage?structuredClone(stage):null,partId:ownerId}}
 function finishClose(){setEditingId(null);setDraftStage(null);setDraftPartId(null);setActive(null);const state=useModelEditorStore.getState();state.cancelManualDetailPlacement();state.cancelRegionPlacement()}
 function discardSnapshot(){const snapshot=snapshotRef.current;if(!snapshot)return;const state=useModelEditorStore.getState();state.restoreManualDetailsSnapshot(snapshot.manualDetails,snapshot.nextManualDetailNumber);if(snapshot.stage)update(snapshot.partId,snapshot.stage.id,{type:snapshot.stage.type,customName:snapshot.stage.customName,paletteColorId:snapshot.stage.paletteColorId,recommendedCoats:snapshot.stage.recommendedCoats,notes:snapshot.stage.notes,targetReferences:snapshot.stage.targetReferences,overviewPreviewEnabled:snapshot.stage.overviewPreviewEnabled,previewShots:snapshot.stage.previewShots});snapshotRef.current=null}
 function cancelEditor(){discardSnapshot();finishClose()}
 function confirmDiscard(){if(!editingId&&!draftStage)return true;if(!window.confirm(t("editor.workflow.discardConfirm")))return false;cancelEditor();return true}
 function edit(id:string){if(editingId===id)return;if(!confirmDiscard())return;const owner=parts.find(item=>item.paintingWorkflow.stages.some(stage=>stage.id===id)),stage=owner?.paintingWorkflow.stages.find(item=>item.id===id);if(!owner||!stage)return;captureSnapshot(owner.id,stage);const state=useModelEditorStore.getState();state.cancelManualDetailPlacement();state.cancelRegionPlacement();if(simpleTargetMode==="parts"){const targetId=stage.targetReferences?.find(reference=>reference.type==="part")?.id??null;if(targetId)selectPart(targetId)}setDraftStage(null);setDraftPartId(owner.id);setEditingId(id);setActive(id)}
 function save(input:Parameters<typeof add>[1]){if(!part)return;if(draftStage)add(part.id,input);else if(editingId){const owner=parts.find(candidate=>candidate.paintingWorkflow.stages.some(stage=>stage.id===editingId));if(owner)update(owner.id,editingId,input)}snapshotRef.current=null;finishClose()}
 function create(){if(!part||editingId||draftStage)return;captureSnapshot(part.id,null);const now=new Date().toISOString(),draft:PaintingStage={id:`draft-${crypto.randomUUID()}`,order:stages.length+1,type:"base-coat",customName:t("editor.workflow.defaultStepTitle"),paletteColorId:null,recommendedCoats:null,notes:"",targetReferences:[],overviewPreviewEnabled:true,previewShots:[],createdAt:now,updatedAt:now};setEditingId(null);setDraftPartId(part.id);setDraftStage(draft);setActive(null)}
 function confirmDelete(){if(!deleting)return;const owner=parts.find(candidate=>candidate.paintingWorkflow.stages.some(stage=>stage.id===deleting.id));if(!owner)return;invalidatePaintingStepPreview(projectId,deleting.id);removeSimpleStep(owner.id,deleting.id);if(editingId===deleting.id){snapshotRef.current=null;finishClose()}setDeleting(null)}
 function copy(stage:PaintingStage){const owner=parts.find(candidate=>candidate.paintingWorkflow.stages.some(item=>item.id===stage.id));if(!owner)return;duplicate(owner.id,stage.id);const id=useModelEditorStore.getState().activePaintingStageId;if(id)setEditingId(id)}
 function startDrag(event:DragEvent<HTMLButtonElement>,stageId:string){if(!part)return;window.getSelection()?.removeAllRanges();event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",stageId);const card=event.currentTarget.closest("article");if(card){const bounds=card.getBoundingClientRect(),overlay=card.cloneNode(true) as HTMLElement,reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;overlay.setAttribute("aria-hidden","true");Object.assign(overlay.style,{position:"fixed",left:"-10000px",top:"-10000px",width:`${bounds.width}px`,height:`${bounds.height}px`,margin:"0",pointerEvents:"none",cursor:"grabbing",opacity:".97",transform:reducedMotion?"none":"scale(1.02)",boxShadow:"0 18px 42px rgba(0,0,0,.28)",zIndex:"9999"});document.body.appendChild(overlay);dragOverlayRef.current=overlay;event.dataTransfer.setDragImage(overlay,Math.max(0,event.clientX-bounds.left),Math.max(0,event.clientY-bounds.top));setDraggedHeight(bounds.height)}setDraggedId(stageId);setDropIndex(stages.findIndex(stage=>stage.id===stageId))}
 function updateDropPosition(event:DragEvent<HTMLLIElement>,index:number){if(!draggedId)return;event.preventDefault();event.dataTransfer.dropEffect="move";const bounds=event.currentTarget.getBoundingClientRect();setDropIndex(event.clientY<bounds.top+bounds.height/2?index:index+1)}
 function finishDrag(){dragOverlayRef.current?.remove();dragOverlayRef.current=null;setDraggedId(null);setDropIndex(null);setDraggedHeight(0)}
 function reorderWithAnimation(stageId:string,targetIndex:number){if(!part)return;preReorderRectsRef.current=new Map([...stepElementsRef.current].map(([id,element])=>[id,element.getBoundingClientRect()]));reorder(part.id,stageId,targetIndex)}
 function drop(event:DragEvent<HTMLLIElement>){event.preventDefault();if(!part||!draggedId||dropIndex===null){finishDrag();return}const sourceIndex=stages.findIndex(stage=>stage.id===draggedId);if(sourceIndex>=0){const targetIndex=Math.max(0,Math.min(stages.length-1,dropIndex>sourceIndex?dropIndex-1:dropIndex));reorderWithAnimation(draggedId,targetIndex)}finishDrag()}
 const counts=getLegacyTargetModeCounts(details),mixed=counts.markers>0&&counts.region>0;
 function chooseMode(mode:SimpleTargetMode){
   const destructive=details.some(detail=>(detail.targetMode==="region"||Boolean(detail.region?.selections.length)?"region":"markers")!==mode&&(detail.pins.length>0||Boolean(detail.region?.selections.length)));
   if(changingMode){
     if(!window.confirm(t("editor.simpleTarget.workflowResetConfirm")))return;
     for(const stage of parts.flatMap(item=>item.paintingWorkflow.stages))invalidatePaintingStepPreview(projectId,stage.id);
   }else if(destructive&&!window.confirm(t(mode==="markers"?"editor.simpleTarget.confirmKeepMarkers":"editor.simpleTarget.confirmKeepRegions")))return;
   applySimpleTargetMode(mode);setChangingMode(false);snapshotRef.current=null;finishClose();
 }
 return <section data-onboarding-target={!simpleTargetMode||changingMode?ONBOARDING_TARGETS.targetingMethod:undefined} className="simple-painting-steps pt-4">
  {!simpleTargetMode||changingMode?<SimpleTargetModeSetup currentMode={simpleTargetMode} mixed={mixed} counts={counts} changing={changingMode} canUseParts={canUseSimplePartColoring(parts)} onCancel={()=>setChangingMode(false)} onContinue={chooseMode}/>:<>
   <div data-onboarding-target={ONBOARDING_TARGETS.targetingMethod} className="flex items-center gap-2.5 rounded-xl border border-[var(--border)] bg-[var(--card)] p-2.5">
    <span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]">{simpleTargetMode==="markers"?<MapPin className="size-3.5"/>:simpleTargetMode==="region"?<Paintbrush className="size-3.5"/>:<Boxes className="size-3.5"/>}</span>
    <span className="min-w-0 flex-1"><span className="block text-[10px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">{t("editor.simpleTarget.settingLabel")}</span><span className="mt-0.5 block truncate text-xs font-semibold text-[var(--text)]">{t(simpleTargetMode==="markers"?"editor.simpleTarget.projectMarkers":simpleTargetMode==="region"?"editor.simpleTarget.projectRegions":"editor.simpleTarget.projectParts")}</span></span>
    <button type="button" onClick={()=>{if(confirmDiscard())setChangingMode(true)}} className="inline-flex min-h-7 cursor-pointer items-center gap-1.5 rounded-lg border border-[var(--border-strong)] bg-transparent px-2.5 text-[10px] font-semibold text-[var(--text-muted)] transition-colors duration-150 hover:border-[var(--accent)] hover:text-[var(--accent)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"><RotateCcw className="size-3"/>{t("common.change")}</button>
   </div>
   {part&&(stages.length||draftStage)?<ol className={`mt-4 space-y-4 ${draggedId?"select-none":""}`}>{[...stages,...(draftStage?[draftStage]:[])].map((stage,index,visibleStages)=>{
    const isDraft=stage.id===draftStage?.id,expanded=isDraft||editingId===stage.id,title=getPaintingStageLabel(stage,t),detailReferences=stage.targetReferences?.filter(reference=>reference.type==="manualDetail")??[],targetDetail=details.find(detail=>detail.id===detailReferences[0]?.id),targetPart=parts.find(candidate=>candidate.id===stage.targetReferences?.find(reference=>reference.type==="part")?.id),color=palette.find(item=>item.id===(simpleTargetMode==="parts"?stage.paletteColorId:targetDetail?.colorId)),targetSummary=stage.type==="primer"?t("editor.workflow.entireModel"):simpleTargetMode==="parts"?targetPart?.name??null:color?.name??targetDetail?.name??null;
    const dragging=draggedId===stage.id,sourceIndex=draggedId?stages.findIndex(item=>item.id===draggedId):-1,targetIndex=sourceIndex<0||dropIndex===null?sourceIndex:Math.max(0,Math.min(stages.length-1,dropIndex>sourceIndex?dropIndex-1:dropIndex)),shift=draggedHeight+16,translate=dragging||sourceIndex===targetIndex?0:sourceIndex<targetIndex&&index>sourceIndex&&index<=targetIndex?-shift:sourceIndex>targetIndex&&index>=targetIndex&&index<sourceIndex?shift:0,showDropBefore=Boolean(draggedId)&&dropIndex===index&&!dragging,showDropAfter=Boolean(draggedId)&&index===stages.length-1&&dropIndex===stages.length&&!dragging;
    return <li key={stage.id} onDragOver={isDraft?undefined:event=>updateDropPosition(event,index)} onDrop={isDraft?undefined:drop} className="relative grid grid-cols-[32px_minmax(0,1fr)] gap-3">
     {showDropBefore?<span aria-hidden="true" className="pointer-events-none absolute -top-2 left-11 right-0 z-10 h-0.5 rounded-full bg-[var(--accent)] shadow-[0_0_0_1px_var(--card)]"/>:null}
     {showDropAfter?<span aria-hidden="true" className="pointer-events-none absolute -bottom-2 left-11 right-0 z-10 h-0.5 rounded-full bg-[var(--accent)] shadow-[0_0_0_1px_var(--card)]"/>:null}
     {index<visibleStages.length-1?<span aria-hidden="true" className={`simple-step-connector absolute bottom-[-1rem] left-[15px] top-7 w-px ${visibleStages[index+1]?.id===draftStage?.id?"is-transitioning":""}`}/>:null}
     <button type="button" onClick={()=>{if(!isDraft)edit(stage.id)}} aria-label={title} aria-pressed={expanded} className={`simple-step-number relative z-[1] grid size-7 cursor-pointer place-items-center self-start rounded-full text-xs font-semibold ${expanded?"is-editing":"is-complete"}`}>{index+1}</button>
     <article data-onboarding-target={expanded?ONBOARDING_TARGETS.stepEditor:undefined} ref={element=>{if(element)stepElementsRef.current.set(stage.id,element);else stepElementsRef.current.delete(stage.id)}} style={{transform:translate?`translateY(${translate}px)`:undefined}} className={`simple-step-card min-w-0 rounded-xl p-3 transition-[opacity,transform] duration-200 ease-out motion-reduce:transition-none ${expanded?"is-selected":""} ${dragging?"opacity-30":""}`}>
      <button type="button" onClick={()=>edit(stage.id)} className="flex w-full cursor-pointer items-start gap-3 text-left">
       <span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[var(--text)]">{title}</span><span className="mt-0.5 block truncate text-[10px] text-[var(--text-muted)]">{getPaintingStageTypeLabel(stage.type,t)}{targetSummary?` · ${targetSummary}`:""}</span></span>
       <span aria-hidden="true" className="size-6 shrink-0 rounded-md border border-[var(--border)]" style={{backgroundColor:color?.hex??"var(--text-muted)"}}/>
      </button>
      {expanded?<><SimplePaintingStepEditor key={stage.id} stage={stage} projectId={projectId} activeReferenceId={props.activeReferenceId} onSelectReference={props.onSelectReference} onShowReference={props.onShowReference} onReferenceDeleted={props.onReferenceDeleted} onClose={cancelEditor} onSave={save}/><ContextualHintSlot id="stepEditor" targetId={ONBOARDING_TARGETS.stepEditor} titleKey="onboarding.hint.step.title" descriptionKey="onboarding.hint.step.description"/></>:<div className="mt-2 flex items-center gap-1">
       <button type="button" draggable onDragStart={event=>startDrag(event,stage.id)} onDragEnd={finishDrag} aria-label={t("editor.steps.actions.drag",{title})} title={t("editor.steps.actions.drag",{title})} className={`simple-step-action grid size-8 place-items-center ${dragging?"cursor-grabbing":"cursor-grab"}`}><GripVertical className="size-4"/></button>
       <button type="button" onClick={()=>edit(stage.id)} aria-label={t("painting.actions.edit")} title={t("painting.actions.edit")} className="simple-step-action grid size-8 cursor-pointer place-items-center"><Pencil className="size-3.5"/></button>
       <button type="button" onClick={()=>copy(stage)} aria-label={t("editor.steps.actions.duplicate")} title={t("editor.steps.actions.duplicate")} className="simple-step-action grid size-8 cursor-pointer place-items-center"><Copy className="size-3.5"/></button>
       <button type="button" disabled={index===0} onClick={()=>reorderWithAnimation(stage.id,index-1)} aria-label={t("editor.steps.actions.moveUp")} title={t("editor.steps.actions.moveUp")} className="simple-step-action grid size-8 cursor-pointer place-items-center disabled:cursor-not-allowed disabled:opacity-35"><ArrowUp className="size-3.5"/></button>
       <button type="button" disabled={index===stages.length-1} onClick={()=>reorderWithAnimation(stage.id,index+1)} aria-label={t("editor.steps.actions.moveDown")} title={t("editor.steps.actions.moveDown")} className="simple-step-action grid size-8 cursor-pointer place-items-center disabled:cursor-not-allowed disabled:opacity-35"><ArrowDown className="size-3.5"/></button>
       <button type="button" onClick={()=>setDeleting(stage)} aria-label={t("editor.steps.actions.delete")} title={t("editor.steps.actions.delete")} className="simple-step-action simple-step-delete grid size-8 cursor-pointer place-items-center"><Trash2 className="size-3.5"/></button>
      </div>}
     </article>
    </li>})}</ol>:<div className="mt-3 rounded-xl border border-[var(--border)] bg-[var(--card)] px-4 py-5 text-center"><span className="mx-auto grid size-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Paintbrush className="size-5"/></span><h3 className="mt-3 text-sm font-semibold text-[var(--text)]">{t("editor.steps.empty")}</h3><p className="mx-auto mt-1 max-w-[17rem] text-xs leading-5 text-[var(--text-muted)]">{t("editor.steps.emptyHelp")}</p></div>}
   <button type="button" data-onboarding-target={ONBOARDING_TARGETS.addStep} disabled={!part||editingId!==null||draftStage!==null} onClick={create} className="simple-add-step mt-3 flex min-h-11 w-full cursor-pointer items-center justify-center gap-2 rounded-xl px-3 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-40"><Plus className="size-4"/>{t("editor.workflow.addStep")}</button>
  </>}
  <ConfirmationModal isOpen={Boolean(deleting)} title={t("editor.steps.delete.title",{title:deleting?getPaintingStageLabel(deleting,t):""})} description={t("editor.steps.delete.description")} confirmLabel={t("editor.steps.actions.delete")} variant="danger" onClose={()=>setDeleting(null)} onConfirm={confirmDelete}/>
 </section>
}
function SimpleTargetModeSetup({currentMode,mixed,counts,changing,canUseParts,onCancel,onContinue}:{currentMode:SimpleTargetMode|null;mixed:boolean;counts:{markers:number;region:number};changing:boolean;canUseParts:boolean;onCancel:()=>void;onContinue:(mode:SimpleTargetMode)=>void}){
 const{t}=useTranslation(),[selected,setSelected]=useState<SimpleTargetMode|null>(changing?currentMode:null);
 return <div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--card)] p-4">{mixed?<><h4 className="text-sm font-semibold">{t("editor.simpleTarget.mixedTitle")}</h4><p className="mt-1 text-xs text-[var(--text-secondary)]">{t("editor.simpleTarget.mixedDescription",{markers:counts.markers,regions:counts.region})}</p></>:<><h4 className="text-sm font-semibold">{t(changing?"editor.region.changeMethod":"editor.simpleTarget.chooseTitle")}</h4><p className="mt-1 text-xs text-[var(--text-secondary)]">{t("editor.simpleTarget.chooseHelp")}</p></>}<p className="mt-2 text-[11px] text-[var(--text-secondary)]">{t(canUseParts?"editor.simpleTarget.partsRecommended":"editor.simpleTarget.partsSingleModel")}</p><div className="mt-3 grid gap-2"><ModeCard mode="markers" selected={selected==="markers"} icon={MapPin} title={t("editor.region.markers")} description={t("editor.simpleTarget.markersDescription")} help={t("editor.simpleTarget.markersBest")} onClick={()=>setSelected("markers")}/><ModeCard mode="region" selected={selected==="region"} icon={Paintbrush} title={t("editor.simpleTarget.regions")} description={t("editor.simpleTarget.regionsDescription")} help={t("editor.simpleTarget.regionsBest")} onClick={()=>setSelected("region")}/><ModeCard mode="parts" selected={selected==="parts"} disabled={!canUseParts} icon={Boxes} title={t("editor.simpleTarget.parts")} description={t("editor.simpleTarget.partsDescription")} help={t(canUseParts?"editor.simpleTarget.partsBest":"editor.simpleTarget.partsUnavailable")} onClick={()=>setSelected("parts")}/></div><div className="mt-4 flex justify-end gap-2">{changing?<button type="button" onClick={onCancel} className="min-h-10 cursor-pointer rounded-lg border border-[var(--border)] bg-[var(--card)] px-4 text-sm font-medium hover:bg-[var(--bg)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">{t("common.cancel")}</button>:null}<button type="button" disabled={!selected||selected===currentMode} onClick={()=>selected&&onContinue(selected)} className="min-h-10 cursor-pointer rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-[var(--accent-foreground)] transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">{t(changing?"editor.simpleTarget.confirmChange":"common.continue")}</button></div></div>
}
function ModeCard({selected,disabled=false,icon:Icon,title,description,help,onClick}:{mode:SimpleTargetMode;selected:boolean;disabled?:boolean;icon:typeof MapPin;title:string;description:string;help:string;onClick:()=>void}){return <button type="button" disabled={disabled} aria-pressed={selected} onClick={onClick} className={`relative flex min-h-24 cursor-pointer items-start gap-3 rounded-xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:cursor-not-allowed disabled:opacity-45 ${selected?"border-[var(--accent)] bg-[color-mix(in_srgb,var(--accent)_12%,var(--card))] ring-1 ring-[var(--accent)]":"border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent)]"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-lg ${selected?"bg-[var(--accent)] text-[var(--accent-foreground)]":"bg-[var(--card)] text-[var(--text-secondary)]"}`}><Icon className="size-4"/></span><span><span className="block text-sm font-semibold text-[var(--text)]">{title}</span><span className="mt-0.5 block text-xs text-[var(--text)]">{description}</span><span className="mt-1 block text-[10px] text-[var(--text-secondary)]">{help}</span></span>{selected?<Check className="absolute right-3 top-3 size-4 text-[var(--accent)]"/>:null}</button>}
