"use client";

import { BookOpen } from "lucide-react";
import Link from "next/link";
import { useTranslation } from "@/features/i18n/hooks/useTranslation";

export function GuidesLoadingState() { const { t } = useTranslation(); return <div role="status" aria-label={t("guides.page.loading")} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item=><div key={item} className="h-80 animate-pulse rounded-2xl border border-[var(--border)] bg-[var(--card)]"/>)}</div>; }
export function GuidesErrorState({ onRetry }: { onRetry: () => void }) { const { t } = useTranslation(); return <div role="alert" className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-6 text-center"><h2 className="text-base font-semibold">{t("guides.errors.title")}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{t("guides.errors.description")}</p><button type="button" onClick={onRetry} className="mt-4 rounded-[10px] bg-[var(--accent)] px-4 py-2 text-sm font-medium text-[var(--accent-foreground)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">{t("guides.errors.retry")}</button></div>; }
export function GuidesEmptyState({ hasModels }: { hasModels: boolean }) { const { t } = useTranslation(); return <div className="flex min-h-80 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--card)] p-6 text-center"><div className="max-w-md"><BookOpen className="mx-auto size-9 text-[var(--accent)]"/><h2 className="mt-4 text-base font-semibold">{t(hasModels?"guides.empty.noGuidesTitle":"guides.empty.noModelsTitle")}</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{t(hasModels?"guides.empty.noGuidesDescription":"guides.empty.noModelsDescription")}</p><Link href="/models" className="mt-5 inline-flex min-h-10 items-center rounded-[10px] bg-[var(--accent)] px-4 text-sm font-medium text-[var(--accent-foreground)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">{t(hasModels?"guides.empty.openModels":"guides.empty.createModel")}</Link></div></div>; }
