"use client";
import { X } from "lucide-react";
import { useEffect } from "react";
import { useTranslation } from "@/features/i18n/hooks/useTranslation";
import { BUILT_IN_GUIDE_TEMPLATES } from "@/features/templates/constants/builtInGuideTemplates";
import { TemplatePreview } from "@/features/templates/components/TemplatePreview";
import type { GuideLibraryTemplate, UserGuideTemplate } from "@/features/templates/types/GuideLibraryTemplate";

export function TemplatePickerModal({currentId,userTemplates,busy,onSelect,onClose}:{currentId:string;userTemplates:readonly UserGuideTemplate[];busy:boolean;onSelect:(id:string)=>Promise<void>;onClose:()=>void}){const{t}=useTranslation();useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy)onClose()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[busy,onClose]);const card=(template:GuideLibraryTemplate)=>{const name=template.source==="builtIn"?t(`templates.presets.${template.nameKey}`):template.name,selected=template.id===currentId;return <article key={template.id} className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-3"><TemplatePreview settings={template.settings}/><h3 className="mt-3 text-sm font-semibold">{name}</h3><p className="mt-1 text-xs text-[var(--text-secondary)]">{t(template.source==="builtIn"?"guide.template.builtIn":"guide.template.mine")}</p><button type="button" disabled={selected||busy} onClick={()=>void onSelect(template.id)} className="mt-3 min-h-10 w-full rounded-[10px] bg-[var(--accent)] px-3 text-sm font-medium text-[var(--accent-foreground)] disabled:border disabled:border-[var(--border)] disabled:bg-[var(--bg)] disabled:text-[var(--text-secondary)]">{selected?t("guide.template.selected"):t("guide.template.apply")}</button></article>};return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[var(--bg)]/95 p-3" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section role="dialog" aria-modal="true" aria-labelledby="template-picker-title" className="max-h-[calc(100dvh-1.5rem)] w-full max-w-4xl overflow-y-auto rounded-2xl border border-[var(--border)] bg-[var(--bg)] p-4 sm:p-6"><header className="flex items-center justify-between"><h2 id="template-picker-title" className="text-lg font-semibold">{t("guide.template.pickerTitle")}</h2><button onClick={onClose} disabled={busy} aria-label={t("common.close")} className="grid size-9 place-items-center"><X className="size-4"/></button></header><h3 className="mt-5 text-sm font-semibold">{t("templates.sections.builtIn")}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{BUILT_IN_GUIDE_TEMPLATES.map(card)}</div><h3 className="mt-6 text-sm font-semibold">{t("templates.sections.mine")}</h3>{userTemplates.length?<div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{userTemplates.map(card)}</div>:<p className="mt-3 text-sm text-[var(--text-secondary)]">{t("guide.template.noUserTemplates")}</p>}</section></div>}
