import type { AssemblyStep } from "@/features/models/types/AssemblyStep";
import type { PaletteColor } from "@/features/models/types/PaletteColor";
import type { ModelPart } from "../types/ModelPart";
import type { PaintingProjectReadiness,PaintingProjectStatistics,PaintingReadinessCheck,PaintingReadinessCheckId } from "../types/PaintingProjectInsights";
import type { PaintingStageType } from "../types/PaintingWorkflow";
import { normalizePaintingOrder } from "./paintingOrder";
const STAGE_TYPES:PaintingStageType[]=["primer","base-coat","secondary-color","wash","dry-brush","highlight","finish","custom"];
export function getPaintingProjectReadiness({parts,palette,paintingOrder,assemblySteps}:{parts:readonly ModelPart[];palette:readonly PaletteColor[];paintingOrder:readonly string[];assemblySteps:readonly AssemblyStep[]}):PaintingProjectReadiness{const included=parts.filter(p=>p.includeInGuide),validColors=new Set(palette.map(c=>c.id)),duplicateCount=paintingOrder.length-new Set(paintingOrder).size,normalized=normalizePaintingOrder({paintingOrder,parts}),missingOrderCount=Math.max(0,parts.length-new Set(paintingOrder.filter(id=>parts.some(p=>p.id===id))).size),missingWorkflows=included.filter(p=>p.paintingWorkflow.stages.length===0).length,invalidColors=included.flatMap(p=>p.paintingWorkflow.stages).filter(s=>s.paletteColorId!==null&&!validColors.has(s.paletteColorId)).length;const checks:Array<[PaintingReadinessCheckId,boolean,number]>=[["painting-order",parts.length>0&&normalized.length===parts.length,missingOrderCount],["palette",palette.length>0,palette.length],["workflows",included.length>0&&missingWorkflows===0,missingWorkflows],["palette-references",invalidColors===0,invalidColors],["order-duplicates",duplicateCount===0,duplicateCount],["order-missing",missingOrderCount===0,missingOrderCount],...(parts.length>1?[["assembly",assemblySteps.length>0,assemblySteps.length] as [PaintingReadinessCheckId,boolean,number]]:[])];const result:PaintingReadinessCheck[]=checks.map(([id,complete,count])=>({id,status:complete?"completed":"warning",count}));const completedCount=result.filter(c=>c.status==="completed").length,warningCount=result.length-completedCount;return{status:warningCount?"attention":"ready",checks:result,warnings:result.filter(c=>c.status==="warning"),completedCount,warningCount,percentage:result.length?Math.round(completedCount/result.length*100):0};}
export function getPaintingProjectStatistics({parts,palette}:{parts:readonly ModelPart[];palette:readonly PaletteColor[]}):PaintingProjectStatistics{const included=parts.filter(p=>p.includeInGuide),stages=included.flatMap(p=>p.paintingWorkflow.stages),workflows=included.filter(p=>p.paintingWorkflow.stages.length>0),timed=included.filter(p=>p.paintingWorkflow.estimatedTimeMinutes!==null),distribution=Object.fromEntries(STAGE_TYPES.map(type=>[type,0])) as Record<PaintingStageType,number>,colorUsage=new Map<string,number>();for(const stage of stages){distribution[stage.type]++;if(stage.paletteColorId)colorUsage.set(stage.paletteColorId,(colorUsage.get(stage.paletteColorId)??0)+1)}const paletteById=new Map(palette.map(c=>[c.id,c]));const mostColor=[...colorUsage].filter(([id])=>paletteById.has(id)).sort((a,b)=>b[1]-a[1])[0],mostType=STAGE_TYPES.map(type=>({type,count:distribution[type]})).sort((a,b)=>b.count-a.count)[0],totalTime=timed.reduce((sum,p)=>sum+(p.paintingWorkflow.estimatedTimeMinutes??0),0);return{totalParts:parts.length,includedParts:included.length,excludedParts:parts.length-included.length,paintingWorkflows:workflows.length,workflowCompletionPercentage:included.length?Math.round(workflows.length/included.length*100):0,totalStages:stages.length,averageStagesPerPart:included.length?stages.length/included.length:0,estimatedTotalTimeMinutes:totalTime,averagePaintingTimeMinutes:timed.length?Math.round(totalTime/timed.length):0,paintBeforeAssemblyCount:included.filter(p=>p.paintingWorkflow.paintBeforeAssembly).length,mostUsedPaletteColor:mostColor?{...paletteById.get(mostColor[0])!,usageCount:mostColor[1]}:null,mostCommonStageType:mostType?.count?mostType:null,stageTypeDistribution:distribution};}
