
import type { Locale } from "@/features/i18n/types/Locale";
import type { PaletteColor } from "@/features/models/types/PaletteColor";
import { DEFAULT_PART_PAINTING_WORKFLOW,type PartPaintingWorkflow,type PaintingDifficulty,type PaintingStage,type PaintingStageType,type PaintingTargetReference } from "../types/PaintingWorkflow";
export const PAINTING_STAGE_TYPES:readonly PaintingStageType[]=["primer","base-coat","secondary-color","wash","dry-brush","highlight","finish","custom"];
const LEGACY_STAGE_TYPES:Record<string,PaintingStageType>={primer:"primer","ґрунтування":"primer","грунтування":"primer","base coat":"base-coat","базовий шар":"base-coat","secondary color":"secondary-color","додатковий колір":"secondary-color",wash:"wash",проливка:"wash",змивка:"wash","dry brush":"dry-brush","суха кисть":"dry-brush",highlight:"highlight",висвітлення:"highlight",finish:"finish","фінішне покриття":"finish",custom:"custom","власний етап":"custom"};
function text(value:unknown){return typeof value==="string"?value.trim():"";}
export function normalizePaintingStageType(value:unknown):PaintingStageType|null{const raw=text(value);if(PAINTING_STAGE_TYPES.includes(raw as PaintingStageType))return raw as PaintingStageType;return LEGACY_STAGE_TYPES[raw.toLocaleLowerCase()]??null;}
export function normalizePaintingStage(value:unknown,index:number):PaintingStage|null{if(!value||typeof value!=="object")return null;const raw=value as Record<string,unknown>;const rawType=text(raw.type),legacyName=text(raw.name),providedCustomName=text(raw.customName);let type=normalizePaintingStageType(rawType);let customName:string|null=null;if(type==="custom")customName=(providedCustomName||legacyName).slice(0,100)||null;else if(!type){if(!rawType)type=normalizePaintingStageType(legacyName);if(type==="custom")customName=(providedCustomName||legacyName).slice(0,100)||null;else if(!type){type="custom";customName=(providedCustomName||rawType||legacyName).slice(0,100)||null;}}if(typeof raw.id!=="string"||!raw.id)return null;const targetReferences=Array.isArray(raw.targetReferences)?raw.targetReferences.flatMap((item):PaintingTargetReference[]=>item&&typeof item==="object"&&((item as {type?:unknown}).type==="part"||(item as {type?:unknown}).type==="marker")&&typeof (item as {id?:unknown}).id==="string"?[{type:(item as {type:"part"|"marker"}).type,id:(item as {id:string}).id}]:[]):[];return{id:raw.id,order:index+1,type,customName,paletteColorId:typeof raw.paletteColorId==="string"?raw.paletteColorId:null,recommendedCoats:Number.isInteger(raw.recommendedCoats)&&Number(raw.recommendedCoats)>=1&&Number(raw.recommendedCoats)<=10?Number(raw.recommendedCoats):null,notes:text(raw.notes).slice(0,500),targetReferences,createdAt:typeof raw.createdAt==="string"?raw.createdAt:"",updatedAt:typeof raw.updatedAt==="string"?raw.updatedAt:""};}
export function normalizePaintingWorkflow(value:unknown):PartPaintingWorkflow{if(!value||typeof value!=="object")return{...DEFAULT_PART_PAINTING_WORKFLOW,stages:[]};const raw=value as Partial<PartPaintingWorkflow>&{stages?:unknown[]};const input=Array.isArray(raw.stages)?raw.stages:[];const stages=input.map((item,index)=>({item,index,order:typeof (item as {order?:unknown})?.order==="number"?Number((item as {order:number}).order):index+1})).sort((a,b)=>a.order-b.order).flatMap(({item},index)=>{const stage=normalizePaintingStage(item,index);return stage?[stage]:[]}).map((stage,index)=>({...stage,order:index+1}));return{stages,notes:text(raw.notes).slice(0,1500),paintBeforeAssembly:raw.paintBeforeAssembly===true,difficulty:["easy","medium","hard"].includes(String(raw.difficulty))?raw.difficulty as PaintingDifficulty:null,estimatedTimeMinutes:Number.isInteger(raw.estimatedTimeMinutes)&&Number(raw.estimatedTimeMinutes)>=1&&Number(raw.estimatedTimeMinutes)<=1440?Number(raw.estimatedTimeMinutes):null};}
export type PaintingWorkflowIssueCode="missing-stage-name"|"invalid-stage-order"|"duplicate-stage-id"|"missing-palette-color"|"invalid-coats"|"invalid-estimated-time";
export type PaintingWorkflowIssue={code:PaintingWorkflowIssueCode;severity:"warning"|"error";stageId:string|null};
export function validatePartPaintingWorkflow({workflow,palette}:{workflow:PartPaintingWorkflow;palette:readonly PaletteColor[]}):PaintingWorkflowIssue[]{const issues:PaintingWorkflowIssue[]=[],ids=new Set<string>(),colors=new Set(palette.map(c=>c.id));workflow.stages.forEach((stage,index)=>{if(stage.type==="custom"&&!stage.customName?.trim())issues.push({code:"missing-stage-name",severity:"error",stageId:stage.id});if(stage.order!==index+1)issues.push({code:"invalid-stage-order",severity:"error",stageId:stage.id});if(ids.has(stage.id))issues.push({code:"duplicate-stage-id",severity:"error",stageId:stage.id});ids.add(stage.id);if(stage.paletteColorId&&!colors.has(stage.paletteColorId))issues.push({code:"missing-palette-color",severity:"warning",stageId:stage.id});if(stage.recommendedCoats!==null&&(!Number.isInteger(stage.recommendedCoats)||stage.recommendedCoats<1||stage.recommendedCoats>10))issues.push({code:"invalid-coats",severity:"error",stageId:stage.id});});if(workflow.estimatedTimeMinutes!==null&&(!Number.isInteger(workflow.estimatedTimeMinutes)||workflow.estimatedTimeMinutes<1||workflow.estimatedTimeMinutes>1440))issues.push({code:"invalid-estimated-time",severity:"error",stageId:null});return issues;}
export function formatPaintingTime(minutes:number,locale:Locale){const h=Math.floor(minutes/60),m=minutes%60;if(!h)return`${m} ${locale==="uk"?"хв":"min"}`;return`${h} ${locale==="uk"?"год":"h"}${m?` ${m} ${locale==="uk"?"хв":"min"}`:""}`;}
