"use client";
import {ChevronLeft,ChevronRight,X} from "lucide-react";
import {useEffect,useRef} from "react";
import {useTranslation} from "@/features/i18n/hooks/useTranslation";
import type {ReferenceImage} from "../types/ReferenceImage";
import {ReferenceImageView} from "./ReferenceImageView";

export function SimpleReferenceViewer({reference,references,onSelect,onClose}:{reference:ReferenceImage;references:ReferenceImage[];onSelect:(id:string)=>void;onClose:()=>void}){
 const{t}=useTranslation(),dialogRef=useRef<HTMLElement>(null),index=references.findIndex(row=>row.id===reference.id);
 useEffect(()=>{const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;dialogRef.current?.querySelector<HTMLElement>("button")?.focus();return()=>previous?.focus()},[]);
 useEffect(()=>{function key(event:KeyboardEvent){if(event.key==="Escape")onClose();else if(event.key==="ArrowLeft"&&index>0)onSelect(references[index-1].id);else if(event.key==="ArrowRight"&&index<references.length-1)onSelect(references[index+1].id);else if(event.key==="Tab"){const buttons=dialogRef.current?.querySelectorAll<HTMLButtonElement>("button:not([disabled])");if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[index,onClose,onSelect,references]);
 return <section ref={dialogRef} role="dialog" aria-modal="true" aria-label={t("simple.references.viewer")} className="fixed inset-0 z-50 flex flex-col bg-neutral-950 text-white"><header className="flex items-center justify-between gap-3 border-b border-white/10 p-4"><div className="min-w-0"><p className="truncate text-sm font-medium">{reference.name}</p><p className="text-xs text-neutral-400">{t("references.position",{current:index+1,total:references.length})}</p></div><button type="button" onClick={onClose} aria-label={t("common.close")} className="rounded-lg p-2"><X className="size-5"/></button></header><div className="flex min-h-0 flex-1 items-center justify-center p-4"><ReferenceImageView blob={reference.blob} alt={reference.name} className="max-h-full max-w-full object-contain"/></div><footer className="flex justify-center gap-6 border-t border-white/10 p-4"><button type="button" disabled={index<=0} onClick={()=>onSelect(references[index-1].id)} aria-label={t("common.previous")} className="rounded-lg p-2 disabled:opacity-30"><ChevronLeft/></button><button type="button" disabled={index>=references.length-1} onClick={()=>onSelect(references[index+1].id)} aria-label={t("common.next")} className="rounded-lg p-2 disabled:opacity-30"><ChevronRight/></button></footer></section>
}
