import { LOCAL_DATABASE_STORES, openLocalDatabase } from "@/features/storage/lib/localDatabase";
import type { CreateUserGuideTemplateInput, GuideTemplateCategory, GuideTemplateSettings, UserGuideTemplate } from "../types/GuideLibraryTemplate";

type StoredTemplate = Omit<UserGuideTemplate,"createdAt"|"updatedAt"> & { createdAt: Date|string|number; updatedAt: Date|string|number };
const STORE=LOCAL_DATABASE_STORES.guideTemplates;
const categories:readonly GuideTemplateCategory[]=["minimal","technical","editorial","custom"];
const settingsValid=(value:unknown):value is GuideTemplateSettings=>Boolean(value&&typeof value==="object"&&typeof (value as GuideTemplateSettings).pageBackground==="string"&&typeof (value as GuideTemplateSettings).textColor==="string"&&typeof (value as GuideTemplateSettings).accentColor==="string");
function normalize(value:unknown):UserGuideTemplate|null{if(!value||typeof value!=="object")return null;const raw=value as Partial<StoredTemplate>;if(typeof raw.id!=="string"||raw.source!=="user"||typeof raw.userId!=="string"||typeof raw.name!=="string"||!categories.includes(raw.category as GuideTemplateCategory)||!settingsValid(raw.settings))return null;const createdAt=new Date(raw.createdAt??0),updatedAt=new Date(raw.updatedAt??0);if(Number.isNaN(createdAt.getTime())||Number.isNaN(updatedAt.getTime()))return null;return{id:raw.id,userId:raw.userId,source:"user",name:raw.name.trim().slice(0,100),category:raw.category as GuideTemplateCategory,settings:raw.settings,createdAt,updatedAt};}
function result<T>(request:IDBRequest<T>):Promise<T>{return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error("Template storage is unavailable."));});}
export const guideTemplateStorage={
  async getByUserId(userId:string){const db=await openLocalDatabase();const records=await result(db.transaction(STORE).objectStore(STORE).index("userId").getAll(userId) as IDBRequest<unknown[]>);return records.flatMap(value=>{const template=normalize(value);return template&&template.userId===userId?[template]:[]});},
  async create(userId:string,input:CreateUserGuideTemplateInput){const db=await openLocalDatabase(),now=new Date();const template:UserGuideTemplate={id:crypto.randomUUID(),userId,source:"user",name:input.name.trim().slice(0,100),category:input.category,settings:{...input.settings},createdAt:now,updatedAt:now};await result(db.transaction(STORE,"readwrite").objectStore(STORE).add(template));return template;},
  async delete(userId:string,id:string){const db=await openLocalDatabase(),store=db.transaction(STORE,"readonly").objectStore(STORE),existing=normalize(await result(store.get(id)));if(!existing||existing.userId!==userId)throw new Error("Template not found.");await result(db.transaction(STORE,"readwrite").objectStore(STORE).delete(id));},
};
