"use client";

import { CheckCircle2, FileBox, UploadCloud } from "lucide-react";
import { useRef, type ChangeEvent } from "react";
import { useTranslation } from "@/features/i18n/hooks/useTranslation";
import { ConfirmationModal } from "@/components/ui/ConfirmationModal";
import type { ModelAnalysis } from "../types/ModelAnalysis";
import type { ModelImportError } from "../types/ModelImportError";
import type { ModelImportStatus } from "../types/ModelImportStatus";
import type { ModelImportWarning } from "../types/ModelImportWarning";
import { ModelImportProgress } from "./ModelImportProgress";
import { ModelImportReport } from "./ModelImportReport";

export function ModelImportFlow({ file, status, progress, stage, analysis, warnings, errors, disabled, heavyConfirmed, onFileSelected, onChooseAnother, onTryAgain, onCancelAnalysis, onConfirmHeavy }: { file: File | null; status: ModelImportStatus; progress: number; stage: string; analysis: ModelAnalysis | null; warnings: ModelImportWarning[]; errors: ModelImportError[]; disabled?: boolean; heavyConfirmed: boolean; onFileSelected: (file: File) => void; onChooseAnother: () => void; onTryAgain: () => void; onCancelAnalysis: () => void; onConfirmHeavy: () => void }) {
  const { t } = useTranslation(), inputRef = useRef<HTMLInputElement>(null);
  const busy = status === "reading" || status === "parsing" || status === "analyzing";
  const needsHeavyConfirmation = status === "review" && analysis?.performanceLevel === "very-heavy" && !heavyConfirmed;
  function change(event: ChangeEvent<HTMLInputElement>) { const next = event.target.files?.[0]; if (next) onFileSelected(next); event.target.value = ""; }
  return <div className="space-y-3"><input ref={inputRef} type="file" accept=".glb,model/gltf-binary,application/octet-stream" disabled={disabled || busy} onChange={change} className="hidden" />{!file ? <button type="button" disabled={disabled} onClick={() => inputRef.current?.click()} className="w-full rounded-2xl border border-dashed border-white/15 bg-white/[.025] px-6 py-9 text-center"><UploadCloud className="mx-auto h-6 w-6 text-orange-400" /><p className="mt-3 text-sm font-medium">{t("modelImport.empty.drop")}</p><p className="mt-1 text-xs text-neutral-500">{t("modelImport.empty.browse")}</p><p className="mt-3 text-xs text-neutral-600">{t("modelImport.empty.limits")}</p></button> : <div className="flex items-center gap-3 rounded-2xl border border-emerald-400/20 bg-emerald-400/5 p-4"><FileBox className="h-5 w-5 text-emerald-400" /><div className="min-w-0 flex-1"><p className="text-xs text-neutral-500">{t("modelImport.selected.title")}</p><p className="truncate text-sm font-medium">{file.name}</p><p className="mt-1 text-xs text-neutral-500">{(file.size / 1024 / 1024).toFixed(1)} MB · GLB{status === "review" ? ` · ${t("modelImport.selected.analysisComplete")}` : ""}</p></div>{status === "review" ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : null}<button type="button" onClick={onChooseAnother} disabled={busy || disabled} className="text-xs text-orange-300">{t("modelImport.actions.chooseAnother")}</button></div>}{busy ? <ModelImportProgress progress={progress} stage={stage} onCancel={onCancelAnalysis} /> : null}{status === "review" && analysis ? <ModelImportReport analysis={analysis} warnings={warnings} onChooseAnother={onChooseAnother} /> : null}{status === "error" ? <div className="rounded-xl border border-red-400/15 bg-red-400/5 p-3"><div className="space-y-1">{errors.map((error, index) => <p key={`${error.code}-${index}`} role="alert" className="text-xs text-red-300">{t(error.messageKey)}</p>)}</div><div className="mt-3 flex gap-2"><button type="button" onClick={onTryAgain} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{t("modelImport.actions.tryAgain")}</button><button type="button" onClick={onChooseAnother} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{t("modelImport.actions.chooseAnother")}</button></div></div> : null}<ConfirmationModal isOpen={needsHeavyConfirmation} title={t("modelImport.confirmations.heavyTitle")} description={t("modelImport.confirmations.heavyDescription")} confirmLabel={t("modelImport.actions.continueAnyway")} onClose={onChooseAnother} onConfirm={onConfirmHeavy} /></div>;
}
